### PR TITLE
Gpio interrupts

### PR DESCRIPTION
**Pull request by bigdinotech**
-add functionality for users to attach callback functions to gpio/pin
interrupts

### CODE REVIEW

**Comment by bigdinotech** [comment]
@SidLeung @eriknyquist ready for review

**Comment by SidLeung** [comment]
@bigdinotech Looks good.  A couple of things to pondering upon.  I know you were working on a way to group the setups into a file/module so that the user app contains mostly the user's code.  I suppose that will be in Beta.  Secondly, do we need to provide some comments/warnings/remarks to the user that call back routines run in the foreground and should execute minimal code (no printing/logging)?

**Comment by bigdinotech** [comment]
@SidLeung I will add the comments on a later PR

**Comment by SidLeung** [comment]
@bigdinotech Thanks!  Please merge @calvinatintel

**Pull request merged**
