### PR TITLE
Optimize and simplify all the examples

### PR DESCRIPTION
**Pull request by bigdinotech**
-optimize configuration of all examples
-remove usb serial functionality for examples that does not require them
-add missing files from some of the examples

### CODE REVIEW

**Comment by bigdinotech** [comment]
@eriknyquist @SidLeung ready for review

**Comment by bigdinotech** [comment]
@eriknyquist please also test the CurieMailbox examples

**Review by eriknyquist — COMMENTED** [review]
Code & re-naming looks good, I'll test it out and approve after that

**Review by eriknyquist — APPROVED** [review]
Tested CurieMailbox samples and a couple x86-only samples, seems to all be working fine.

**Pull request merged**
