### PR TITLE
pwm wrapper changes

### PR DESCRIPTION
**Pull request by bigdinotech**
-modify pwm wrapper to be compatible with Zephyr 1.5
-add pwmWriteResolution functionality

### CODE REVIEW

**Comment by bigdinotech** [comment]
@eriknyquist @SidLeung please review
@calvinatintel please do NOT merge until CODK-M is rebased to Zephyr 1.5

**Comment by calvinatintel** [comment]
Updated CODK-M to Zephyr 1.5. Please review.

**Comment by bigdinotech** [comment]
@eriknyquist @SidLeung. Please review now that we have rebased to Zephyr 1.5

**Review by eriknyquist — APPROVED** [review]

**Comment by calvinatintel** [comment]
cherry-picked

**Pull request closed without merging**
