### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by bigdinotech**
-refactored code to simply the main code
-separated the cdc-acm serial code and tasks
-separated functions the control the soc cores

### CODE REVIEW

**Comment by bigdinotech** [comment]
@SidLeung @eriknyquist ready for review

**Comment by bigdinotech** [comment]
@eriknyquist please review this one also. It has the same changes to the other repo

**Comment by SidLeung** [comment]
@bigdinotech Love it!  It's so clean now.  BTW, would you consider making a grouping routine, say, platformInit() or something similar, to gather up all the initialization calls and thread invokings?  Those calls are pretty much needed in most applications, right?

**Comment by bigdinotech** [comment]
@calvinatintel please merge
@SidLeung I'll do that on my next round of cleanup

**Comment by SidLeung** [comment]
@bigdinotech Many thanks.

**Pull request merged**
